// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABczGR9l0tz57cCtX_r6BNwkuZt0hxc6I',
    appId: '1:978146309733:web:24dbe83d752ccb5720f88c',
    messagingSenderId: '978146309733',
    projectId: 'fir-auth-37000',
    authDomain: 'fir-auth-37000.firebaseapp.com',
    databaseURL: 'https://fir-auth-37000-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-37000.appspot.com',
    measurementId: 'G-YC1BBHR7ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjaj7KkWUUidau16D1wkskoDdKO-WgGU',
    appId: '1:978146309733:android:519f6b9121c76fed20f88c',
    messagingSenderId: '978146309733',
    projectId: 'fir-auth-37000',
    databaseURL: 'https://fir-auth-37000-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-37000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxeEK00Hhs-rFANUuvbjSzLbtK7r9jIJk',
    appId: '1:978146309733:ios:8bc435957b6c640e20f88c',
    messagingSenderId: '978146309733',
    projectId: 'fir-auth-37000',
    databaseURL: 'https://fir-auth-37000-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-37000.appspot.com',
    iosClientId: '978146309733-48a7rqm3cigt14ef379ndl720he44nbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.travo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxeEK00Hhs-rFANUuvbjSzLbtK7r9jIJk',
    appId: '1:978146309733:ios:cccaa3d8f4af95d420f88c',
    messagingSenderId: '978146309733',
    projectId: 'fir-auth-37000',
    databaseURL: 'https://fir-auth-37000-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-auth-37000.appspot.com',
    iosClientId: '978146309733-h855gl5f41aupp4hsgnv04sh071iv9hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.travo.RunnerTests',
  );
}
